### ISSUE TITLE
Scale up to million of nodes

### ISSUE THREAD

**Issue by jthsieh** [tkipf/pygcn#14]
Hi @tkipf, thank you so much for providing the code.

I'm wondering if it's possible to scale this implementation up to millions of nodes (obviously the number of edges must scale linearly), for example a grid. I'm not familiar with PyTorch's sparse matrix implementation, so I'm not sure if representing the adjacency matrix as a sparse matrix is enough to deal with large graphs?

**Comment by tkipf** [comment]
For large datasets, have a look at the sampling strategy from FastGCN:
https://arxiv.org/abs/1801.10247

This should be relatively easy to implement. Essentially just sample an
adjacency and feature matrix (with importance sampling) every training step.

**Comment by jthsieh** [comment]
Thank you! What if I want to use it on the entire graph?

I guess I just want to confirm:
Let's say I have a graph with N nodes and O(N) edges, and `adj` is the adjacency matrix of type `torch.sparse.FloatTensor`. Does `torch.spmm(adj, x)` run in O(N) time?

**Comment by tkipf** [comment]
It runs in O(E) time where E is the number of edges (assuming that E>N)

**Comment by jthsieh** [comment]
Thank you!
