### ISSUE TITLE
Why test sample number is much more than train / validation sample? 

### ISSUE THREAD

**Issue by zhiqiangzhongddu** [tkipf/pygcn#17]
I saw you assign train/val/test follow this way:
idx_train = range(140)
idx_val = range(200, 500)
idx_test = range(500, 1500)

I don't understand why you assign test sample number much more than train and val?

**Comment by tkipf** [comment]
To get a more reliable estimate of the test error :-)

**Comment by zhiqiangzhongddu** [comment]
I see, thank you for the response.

**Comment by IreneZihuiLi** [comment]
Are these ids true ids in the cora cites dataset?
Or they are just from 0 to 1500.
Also, why id 140-200 were not chosen?

**Comment by tkipf** [comment]
These IDs don't reflect original paper IDs in Cora. We only select 140
labels (20 per class) to match the size of the splits used in our paper. No
particularly striking reason for omitting IDs 140-200 apart from getting
some "nicer" round numbers ;)

**Comment by IreneZihuiLi** [comment]
Thanks!
