### ISSUE TITLE
The cora sites graph is not connected?

### ISSUE THREAD

**Issue by bapriddy** [tkipf/pygcn#29]
@tkipf 

When I displayed the graph I got a graph with many components.  Is this correct?  pdf attached.  Maybe you included extra info in the edge list?

[cora.pdf](https://github.com/tkipf/pygcn/files/2753108/cora.pdf)

**Comment by tkipf** [comment]
Yes this should be fine. If I remember correctly the benchmark dataset
version of Cora had multiple connected components.

**Comment by bapriddy** [comment]
Got it.  Thanks!

**Comment by ZHUXUHAN** [comment]
> @tkipf
> 
> When I displayed the graph I got a graph with many components. Is this correct? pdf attached. Maybe you included extra info in the edge list?
> 
> [cora.pdf](https://github.com/tkipf/pygcn/files/2753108/cora.pdf)

hello
can you tell me how to visualize the data?

**Comment by preetham-salehundam** [comment]
> @tkipf
> 
> When I displayed the graph I got a graph with many components. Is this correct? pdf attached. Maybe you included extra info in the edge list?
> 
> [cora.pdf](https://github.com/tkipf/pygcn/files/2753108/cora.pdf)

How did you plot the graph?

**Comment by bapriddy** [comment]
@tkipf @ZHUXUHAN @preetham-salehundam
My apologies for not responding sooner!  I used mathematica (below) for this but there are many other ways.  Gephi is a free open source code that installs quickly.  You could probably use python...

```
M := Import["cora", "Table"];
Ev := EdgeList[M];
g := Graph[Ev];
A := AdjacencyMatrix[g]
G := AdjacencyGraph[A];
GraphPlot[G]
```

**Comment by bapriddy** [comment]
solved.
