### ISSUE TITLE
build symmetric adjacency matrix

### ISSUE THREAD

**Issue by laoreja** [tkipf/pygcn#3]
Hi tkipf, thank you for your amazing work!
in utils.py, starts from Line 36,

```Python
    # build symmetric adjacency matrix
    adj = adj + adj.T.multiply(adj.T > adj) - adj.multiply(adj.T > adj)
```

As far as I understand, these lines are turning a directed adjacency matrix into an undirected adjacency matrix?
Since adj is a 0-1 matrix, then for the positions `adj[i,j]` where  `adj.T > adj`,  we should have `adj[i,j] = 0`, so the `- adj.multiply(adj.T > adj)` part is always zero.

Then what's the purpose of having that part, or am I understand it incorrectly?

**Comment by tkipf** [comment]
Yes, for binary adjacency matrices you are right. In all other cases you need the last term to ensure that only a single edge is kept (the one with largest weight).

**Comment by fansariadeh** [comment]
I do not understand why adj matrix should be turned into a symmetric matrix. Could you please clarify it?

**Comment by baojianzhou** [comment]
@fansariadeh. Based on my understanding, the original [GCN paper](https://arxiv.org/pdf/1609.02907.pdf) considers undirected graphs. In some datasets, the graph may not be undirected ( e.g. store as the directed graph). This line of code can make sure the input graph be undirected.

**Comment by Jingdong-Liu** [comment]
https://github.com/yao8839836/text_gcn/issues/17

**Comment by fansariadeh** [comment]
> @fansariadeh. Based on my understanding, the original [GCN paper](https://arxiv.org/pdf/1609.02907.pdf) considers undirected graphs. In some datasets, the graph may not be undirected ( e.g. store as the directed graph). This line of code can make sure the input graph be undirected.

Dear @baojianzhou 
That makes sense to me now. I appreciate it.
Cheers,
