### ISSUE TITLE
Question about adj

### ISSUE THREAD

**Issue by zdaiot** [tkipf/pygcn#37]
In your code, use below code to create adj matrix
```
    adj = sp.coo_matrix((np.ones(edges.shape[0]), (edges[:, 0], edges[:, 1])),
                        shape=(labels.shape[0], labels.shape[0]),
                        dtype=np.float32)
```
That means`adj[edges[:, 0][k], edges[:, 1][k]] = np.ones(edges.shape[0])[k]`. But in the file `data/cora/README`,  it says that the direction of the link is from right to left. Details are as follows：
```
The .cites file contains the citation graph of the corpus. Each line describes a link in the following format:

		<ID of cited paper> <ID of citing paper>

Each line contains two paper IDs. The first entry is the ID of the paper being cited and the second ID stands for the paper which contains the citation. The direction of the link is from right to left. If a line is represented by "paper1 paper2" then the link is "paper2->paper1". 
```

I would like to ask why the code that produces the adjacency matrix is not like this：
```
    adj = sp.coo_matrix((np.ones(edges.shape[0]), (edges[:, 1], edges[:, 0])),
                        shape=(labels.shape[0], labels.shape[0]),
                        dtype=np.float32)
```
That means`adj[edges[:, 1][k], edges[:, 0][k]] = np.ones(edges.shape[0])[k]`.

Thanks a lot ~

**Comment by tkipf** [comment]
The graph is later treated as undirected, so the edge direction in this part of the script is arbitrary
