### ISSUE TITLE
Question normalization trick

### ISSUE THREAD

**Issue by diegoantognini** [tkipf/pygcn#4]
Dear authors,

I was wondering why in the function normalize, the power is to -1 and not -1/2 as in the tensorflow code. Is there any reason for this ?

Thanks for the answer !

**Comment by tkipf** [comment]
I found that both have similar performance in practice and wanted to provide some variation in this implementation. Feel free to use the symmetric normalization from the original paper, though. Shouldn't affect results too much

**Comment by diegoantognini** [comment]
Great, thank you for your answer !
