### ISSUE TITLE
 Chebyshev convolution in Pytroch and its kernel size

### ISSUE THREAD

**Issue by pinkfloyd06** [tkipf/pygcn#5]
Hello,

In your Pytorch version, where the Chebyshev convolution is implemented ? 

l don't find it in https://github.com/tkipf/pygcn/tree/master/pygcn

l would like to see the kernel size of convolutional filters
Thank you

**Comment by tkipf** [comment]
It's not implemented. Feel free to submit a PR.

**Comment by pinkfloyd06** [comment]
Great, which convolution is used so ?
l don't see any convolution and pooling in your implementation

**Comment by swg209** [comment]
@pinkfloyd06  Hi, have you implement the code of Chebyshev convolution?
