### ISSUE TITLE
Still curious about the code of building symmetric adjacency matrix 

### ISSUE THREAD

**Issue by BilyZ98** [tkipf/pygcn#54]
`    adj = sp.coo_matrix((np.ones(edges.shape[0]), (edges[:, 0], edges[:, 1])),
                        shape=(labels.shape[0], labels.shape[0]),
                        dtype=np.float32)

    # build symmetric adjacency matrix
    adj = adj + adj.T.multiply(adj.T > adj) - adj.multiply(adj.T > adj)`

I don't understand how the last line code produces the symmetric matrix.
And I think it is intuitive to build the symmetric like this
`adj = adj + adj.T`

Can anyone help to answer my questions? thanks a lot

**Comment by BilyZ98** [comment]
ok now I understand. the multiply is a point-wise multiplication, not a matrix product.

**Comment by Spico197** [comment]
> ok now I understand. the multiply is a point-wise multiplication, not a matrix product.

Sorry, mate. I have the same problem here. Why can't we just use `adj + adj.T` to create the symmetric matrix? thx.

**Comment by Spico197** [comment]
> ok now I understand. the multiply is a point-wise multiplication, not a matrix product.

Hi, mate. I have the same problem here. I'm curious why we have to subtract `adj.multiply(adj.T > adj)`? Entries in `adj.multiply(adj.T > adj)` should be all zeros.

**Comment by Pager07** [comment]
> > ok now I understand. the multiply is a point-wise multiplication, not a matrix product.
> 
> Hi, mate. I have the same problem here. I'm curious why we have to subtract `adj.multiply(adj.T > adj)`? Entries in `adj.multiply(adj.T > adj)` should be all zeros.

https://github.com/tkipf/pygcn/issues/3
